import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/lib/provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Toaster
          position="top-right"
          theme="light"
          toastOptions={{
            unstyled: true,
            classNames: {
              success:
                "bg-green-600 rounded-lg py-2 px-4 shadow-lg text-white w-96 flex gap-2 items-center content-center",
            },
          }}
        />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
